// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechDashboardAPI.Infrastructure.Data;

#nullable disable

namespace TechDashboardAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811124536_UpdateEntityRelationships")]
    partial class UpdateEntityRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DepartmentHeadId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Departments_CreatedBy");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_DepartmentCode")
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.HasIndex("DepartmentHeadId")
                        .HasDatabaseName("IX_Departments_DepartmentHeadId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Departments_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Name");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FormFields_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FormFields_Name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_FormFields_ProjectId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_FormFields_Type");

                    b.HasIndex("ProjectId", "IsActive")
                        .HasDatabaseName("IX_FormFields_Project_IsActive");

                    b.HasIndex("ProjectId", "Order")
                        .HasDatabaseName("IX_FormFields_Project_Order");

                    b.ToTable("FormFields", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Problems_CreatedBy");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_Problems_CreatedDate");

                    b.HasIndex("LikeCount")
                        .HasDatabaseName("IX_Problems_LikeCount");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Problems_Priority");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Problems_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Problems_Status");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Problems_Title");

                    b.HasIndex("IsActive", "Status")
                        .HasDatabaseName("IX_Problems_IsActive_Status");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("IX_Problems_Project_Status");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("IX_Problems_Status_Priority");

                    b.ToTable("Problems", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId")
                        .HasDatabaseName("IX_ProblemFieldValues_FormFieldId");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("IX_ProblemFieldValues_ProblemId");

                    b.HasIndex("ProblemId", "FormFieldId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProblemFieldValues_Problem_FormField");

                    b.ToTable("ProblemFieldValues", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FormFields")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_ProblemForms_CreatedBy");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ProblemForms_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ProblemForms_Name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ProblemForms_ProjectId");

                    b.HasIndex("ProjectId", "IsActive")
                        .HasDatabaseName("IX_ProblemForms_Project_IsActive");

                    b.ToTable("ProblemForms", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ProblemLikes_CreatedDate");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("IX_ProblemLikes_ProblemId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ProblemLikes_UserId");

                    b.HasIndex("ProblemId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProblemLikes_Problem_User");

                    b.ToTable("ProblemLikes", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Projects_CreatedBy");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Projects_DepartmentId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Projects_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Projects_Name");

                    b.HasIndex("ProjectManagerId")
                        .HasDatabaseName("IX_Projects_ProjectManagerId");

                    b.HasIndex("DepartmentId", "IsActive")
                        .HasDatabaseName("IX_Projects_Department_IsActive");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Projects_DateRange")
                        .HasFilter("[StartDate] IS NOT NULL AND [EndDate] IS NOT NULL");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AzureDevOpsLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("IX_Solutions_ApprovedBy");

                    b.HasIndex("ApprovedDate")
                        .HasDatabaseName("IX_Solutions_ApprovedDate")
                        .HasFilter("[ApprovedDate] IS NOT NULL");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_Solutions_CreatedDate");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("IX_Solutions_ProblemId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Solutions_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Solutions_UserId");

                    b.HasIndex("ProblemId", "Status")
                        .HasDatabaseName("IX_Solutions_Problem_Status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Solutions_User_Status");

                    b.ToTable("Solutions", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Users_DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("IsActive", "Role")
                        .HasDatabaseName("IX_Users_IsActive_Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Department", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DepartmentHead");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.FormField", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.Project", "Project")
                        .WithMany("FormFields")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Problem", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "CreatedByUser")
                        .WithMany("Problems")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.Project", "Project")
                        .WithMany("Problems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemFieldValue", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.FormField", "FormField")
                        .WithMany()
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.Problem", "Problem")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemForm", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.Project", "Project")
                        .WithMany("ProblemForms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.ProblemLike", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemLikes")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "User")
                        .WithMany("ProblemLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Project", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Solution", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechDashboardAPI.Domain.Entities.Problem", "Problem")
                        .WithMany("Solutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechDashboardAPI.Domain.Entities.User", "User")
                        .WithMany("Solutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("TechDashboardAPI.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechDashboardAPI.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Problem", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("ProblemLikes");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.Project", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("ProblemForms");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("TechDashboardAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("ProblemLikes");

                    b.Navigation("Problems");

                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
